don't add route if conflict with wg interface

diff --git a/root/etc/s6-overlay/s6-rc.d/init-wireguard/run b/root/etc/s6-overlay/s6-rc.d/init-wireguard/run
--- a/root/etc/s6-overlay/s6-rc.d/init-wireguard/run
+++ b/root/etc/s6-overlay/s6-rc.d/init-wireguard/run
@@ -164,6 +164,17 @@ fi
 IFS=',' read -ra lan_networks <<< "${VPN_LAN_NETWORK%,}"
 for lan_network in "${lan_networks[@]}"; do
     lan_network="${lan_network//[[:space:]]/}"
+    lan_net=$(getnet "${lan_network}" || true)
+    lan_prefix=$(getprefix "${lan_network}" || true)
+    networks=$(jq -rc --arg interface "${VPN_CONF}" '.[]|select((.ifname==$interface))|.addr_info[]' <<< "${ip_addr_json}")
+    while IFS=$'\n' read -r network; do
+        local=$(jq -r '.local' <<< "${network}")
+        net=$(getnet "${local}/${lan_prefix}" || true)
+        network_list_wg+="${net},"
+        [[ "${lan_net}" == "${net}" ]] && [[ -n "${lan_net}" ]] && [[ -n "${net}" ]] && \
+            log_wrn "[VPN] Could not add route for [${lan_network}][LAN] due to conflict with address [${local}] on interface [${VPN_CONF}]." && break
+    done <<< "${networks}"
+    grep -q "${lan_net}" <<< "${network_list_wg}" && continue
     if valid4 "${lan_network}" && valid4 "${default4_gateway}"; then
         ip -4 route add "${lan_network}" via "${default4_gateway}" dev "${default4_interface}"
         log_inf "[VPN] Routing IPv4 traffic for [${lan_network}][LAN] via interface [${default4_interface}]."
