reduce vpn log spam

diff --git a/root/etc/s6-overlay/s6-rc.d/service-pia/run b/root/etc/s6-overlay/s6-rc.d/service-pia/run
--- a/root/etc/s6-overlay/s6-rc.d/service-pia/run
+++ b/root/etc/s6-overlay/s6-rc.d/service-pia/run
@@ -9,21 +9,26 @@ while true; do
         pf_hostname=$(jq -r '.hostname' < "${CONFIG_DIR}/wireguard/${VPN_CONF}.json")
         pf_gateway=$(jq -r '.ip' < "${CONFIG_DIR}/wireguard/${VPN_CONF}.json")
 
-        pia_token=""
         while [[ -z "${pia_token}" ]]; do
-            echo "[INFO] [$(date '+%Y-%m-%d %H:%M:%S')] [PIA] Token retrieval started..."
-            PIA_USER=${VPN_PIA_USER} PIA_PASS=${VPN_PIA_PASS} ./get_token.sh > /dev/null
-            touch /opt/piavpn-manual/token
-            pia_token=$(head -1 /opt/piavpn-manual/token)
+            echo "[INFO] [$(date '+%Y-%m-%d %H:%M:%S')] [PIA] Fetching token..."
+            pia_token_response=$(PIA_USER=${VPN_PIA_USER} PIA_PASS=${VPN_PIA_PASS} ./get_token.sh)
+            if grep -q PIA_TOKEN= <<< "${pia_token_response}" && ! grep -q PIA_TOKEN=null <<< "${pia_token_response}"; then
+                pia_token=$(grep PIA_TOKEN= <<< "${pia_token_response}" | awk -F '=' '{print $2}')
+                echo "[INFO] [$(date '+%Y-%m-%d %H:%M:%S')] [PIA] Token received."
+            else
+                echo "[ERROR] [$(date '+%Y-%m-%d %H:%M:%S')] [PIA] Fetching token failed! Re-trying in 10 seconds..."
+                sleep 10
+            fi
         done
 
         pia_response=$(curl --interface "${VPN_CONF}" -Gs -m 5 --connect-to "$pf_hostname::$pf_gateway:" --cacert "ca.rsa.4096.crt" --data-urlencode "token=${pia_token}" "https://${pf_hostname}:19999/getSignature")
         if [[ $(echo "${pia_response}" | jq -r '.status') == "OK" ]]; then
-            pia_payload=$(echo "${pia_response}" | jq -r .payload)
-            pia_signature=$(echo "${pia_response}" | jq -r .signature)
-            pia_payload_decoded=$(echo "${pia_payload}" | base64 -d | jq)
-            pia_port=$(echo "${pia_payload_decoded}" | jq -r .port)
-            pia_port_expiration=$(echo "${pia_payload_decoded}" | jq -r .expires_at)
+            pia_payload=$(jq -r '.payload' <<< "${pia_response}")
+            pia_signature=$(jq -r '.signature' <<< "${pia_response}")
+            pia_payload_decoded=$(base64 -d <<< "${pia_payload}")
+            pia_port=$(jq -r '.port' <<< "${pia_payload_decoded}")
+            pia_port_expiration=$(jq -r '.expires_at' <<< "${pia_payload_decoded}")
+            echo "[INFO] [$(date '+%Y-%m-%d %H:%M:%S')] [PIA] Forwarded port is \"${pia_port}\", will expire at \"${pia_port_expiration}\"."
             touch "${CONFIG_DIR}/wireguard/forwarded_port"
             old_port=$(cat "${CONFIG_DIR}/wireguard/forwarded_port")
             if [[ "${pia_port}" != "${old_port}" ]]; then
@@ -31,19 +36,12 @@ while true; do
                 # shellcheck source=/dev/null
                 source "${APP_DIR}/forwarded_port_update_app"
             fi
-            echo "[INFO] [$(date '+%Y-%m-%d %H:%M:%S')] [PIA] Forwarded port is \"${pia_port}\", will expire at \"${pia_port_expiration}\"."
-            diff=100
-            while [[ ${diff} -gt 2 ]]; do
+            while [[ $(date -d "${pia_port_expiration}" +%s) -gt $(date -d "$(date)" +%s) ]]; do
                 bind_port_response="$(curl --interface "${VPN_CONF}" -Gs -m 5 --connect-to "$pf_hostname::$pf_gateway:" --cacert "ca.rsa.4096.crt" --data-urlencode "payload=${pia_payload}" --data-urlencode "signature=${pia_signature}" "https://${pf_hostname}:19999/bindPort")"
-                if [[ $(echo "${bind_port_response}" | jq -r '.status') == "OK" ]]; then
-                    echo "[INFO] [$(date '+%Y-%m-%d %H:%M:%S')] [PIA] Port bind succeeded."
-                else
+                if ! [[ $(jq -r '.status' <<< "${bind_port_response}") == "OK" ]]; then
                     echo "[WARNING] [$(date '+%Y-%m-%d %H:%M:%S')] [PIA] Port bind failed!"
+                    break
                 fi
-                date_one=$(date -d "${pia_port_expiration}" +%s)
-                date_two=$(date -d "$(date)" +%s)
-                diff=$(( (date_one - date_two) / 86400 ))
-                echo "[INFO] [$(date '+%Y-%m-%d %H:%M:%S')] [PIA] Port still valid for ${diff} days."
                 sleep 900
             done
         else
